name: pydev
services:
  app:
    container_name: goo
    build: .
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: bash
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg2
      - DOCKER_INFLUXDB_INIT_BUCKET=tick_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123



